name: 
  Test input in an if in a job step.

description:
  Basic test
  
inputs:
  SOME_VARIABLE:
    required: false
    default: ''
    description: "'Boolean' input variable"

runs:
  using: "composite"
  steps:
    - name: Test_if
      if: inputs.SOME_VARIABLE
      shell: bash
      run: echo No!! This should not run
