name: "Recreate CGo Zig bug on Mac-OS 12 and 13"

on:
  workflow_dispatch:

jobs:
  build:
    name: "Try to compile"
    strategy:
      matrix:
        os: ["ubuntu-24.04", "windows-2022", "macos-12", "macos-13", "macos-14"]
    runs-on: matrix.os
    
    steps:
    - uses: actions/checkout@v4

    - name: Install Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.13.0
        
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Compile
      run: |
        go env -w "CC=zig cc"
        go build -o hello main.go

    - name: Output Go version
      run: go version


    - name: upload_output
      id: installer-upload-step
      uses: actions/upload-artifact@v4
      with:
        name: output_${{ matrix.os }}
        path: .
