name: "Try to recreate CGo Zig bug"

on:
  workflow_dispatch:

  push:


  pull_request:


jobs:
  build_and_run:
    name: Try to compile on windows
    runs-on: windows-2022
    
    steps:
    - uses: actions/checkout@v4

    - name: Install Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.13.0

    - name: Compile
      shell: bash
      run: CC='zig cc' go build main.go

    - name: Output Go version
      run: go --version

      
