name: "If: input.var Action test."

on:
  workflow_dispatch:

  push:

jobs:

  test_installer:



    name: "Run test action. "
    
    runs-on: "ubuntu-24.04"


    steps:

    - uses: actions/checkout@v4
    
    - name: Run test 
      uses: ./.github/actions/test_if_input
      with:
        SOME_VARIABLE: true 
