name: "Run R"

on:
  workflow_dispatch:


jobs:
  build_and_upload_installer:
    # strategy:
      # matrix:
      #   os: ["windows-2022", "ubuntu-24.04"]
    name: Try to compile on Ubuntu with CMake
    runs-on: ubuntu-24.04
    steps:
    - run: Rscript --version
