name: "Run Git rev-parse Head"

on:
  workflow_dispatch:


jobs:
  build_and_upload_installer:
    name: Try to compile on Ubuntu with CMake
    runs-on: "ubuntu-24.04"
    steps:
    - uses: actions/checkout@v4

    - name: env var test
      run: |
        NEW_PATH=$PATH
        echo $NEW_PATH

    - run: echo $VCPKG_ROOT

    - run: echo $VCPKG_INSTALLATION_ROOT

    - run: |
        cmake -E env VCPKG_ROOT=$VCPKG_INSTALLATION_ROOT
        echo $VCPKG_ROOT

    - run: cmake --version

    - name: run git rev-parse HEAD
      run: git rev-parse HEAD

    - name: run git rev-parse HEAD in Python
      run: python -c "import subprocess; print(subprocess.run('git rev-parse HEAD', shell=True))"
