name: "Run R"

on:
  workflow_dispatch:


jobs:
  build_and_upload_installer:
    # strategy:
      # matrix:
      #   os: ["windows-2022", "ubuntu-24.04"]
    name: Run Rscript --version
    runs-on: ubuntu-24.04
    steps:
    - name: Install R and deps
      run: |
        sudo apt-get update
        sudo apt-get install -y r-cran-optparse r-cran-sjstats
    - run: Rscript --version
